site_name: OpenAgent
site_description: AI-powered terminal assistant with Hugging Face integration - open source alternative to Warp AI
site_url: https://geneticxcln.github.io/OpenAgent

repo_name: GeneticxCln/OpenAgent
repo_url: https://github.com/GeneticxCln/OpenAgent

nav:
  - Home: README.md
  - Getting Started: 
    - Installation: docs/installation.md
    - Quick Start: docs/quickstart.md
  - Documentation:
    - API Reference: docs/api.md
    - Configuration: docs/configuration.md
    - Architecture: docs/architecture.md
  - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GeneticxCln/OpenAgent
