name: 🚀 Feature Request
description: Suggest a new feature or enhancement for OpenAgent
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see added.
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Use Case
      description: Why do you need this feature? What problem does it solve?
      placeholder: "This would help me..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? Include any specific implementation ideas.
      placeholder: "I think it should work like..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've also considered..."
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature primarily affect?
      options:
        - Core Agent System
        - LLM Integration
        - Tools System
        - Security/Policy Engine
        - CLI Interface
        - Web API/Server
        - WebSocket Interface
        - Plugin System
        - Documentation
        - Testing
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Important for my use case
        - Critical - Blocking my use case
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I would prefer someone else implements this

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, screenshots, or examples about the feature request.
      placeholder: "Here are some examples or additional details..."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, I agree to the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have provided enough detail for the development team to understand the request
          required: true
        - label: I understand this is a feature request and may take time to implement
          required: true
