name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have checked the roadmap and this isn't already planned
          required: true
        - label: This feature would benefit the broader OpenAgent community
          required: true

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're facing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe your proposed solution
      placeholder: How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: What alternatives have you considered?
      placeholder: Describe alternative solutions you've thought about...

  - type: textarea
    id: use_cases
    attributes:
      label: 🎪 Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a [user type], I want to [action] so that [benefit]
        2. When [scenario], this feature would [benefit]
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: 📝 Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        ```bash
        # Example command or usage
        openagent new-feature --option value
        ```

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve workflow"
        - "High - Significantly impacts productivity"
        - "Critical - Blocking current work"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: ⚙️ Estimated Complexity
      description: How complex do you think this feature is to implement?
      options:
        - "Low - Simple addition or modification"
        - "Medium - Moderate development effort"
        - "High - Significant development effort"
        - "Unknown - Not sure about complexity"

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help with testing
        - label: I would be willing to help with documentation
        - label: I can provide domain expertise/guidance

  - type: textarea
    id: additional
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the feature request
      placeholder: Any additional information, mockups, or references...
