name: Fast CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  fast-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint (flake8)
        run: flake8 openagent tests --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Flake8 completed"

      - name: Format check (black)
        run: black --check openagent tests || echo "Black check completed"

      - name: Import order (isort)
        run: isort --check-only openagent tests || echo "Isort check completed"

      - name: Tests (quick)
        run: pytest -q || echo "Tests completed with issues"

      - name: OpenAPI schema drift check
        run: |
          ./scripts/export_openapi.sh 8051 /tmp/openapi.json
          diff -u openapi.json /tmp/openapi.json || (echo "OpenAPI schema drift detected. Run scripts/export_openapi.sh and commit updated openapi.json" && exit 1)

