name: Nightly Full Matrix

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  nightly:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint (flake8)
        run: flake8 openagent tests
      - name: Format check (black)
        run: black --check openagent tests
      - name: Import order (isort)
        run: isort --check-only openagent tests
      - name: Type check (mypy)
        run: mypy openagent
      - name: Tests with coverage
        run: pytest -q --cov=openagent --cov-report=xml --cov-report=term
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python-version }}
          path: coverage.xml

